# Generated by Django 4.2.1 on 2023-05-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data_mod',
        ),
    ]
