# Generated by Django 4.2.1 on 2023-05-25 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_delete_teste_remove_nota_data_remove_nota_data_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
