# Generated by Django 4.2.1 on 2023-06-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_task_delete_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='corpo',
            new_name='taks',
        ),
    ]
