# Generated by Django 4.2.1 on 2023-06-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_rename_corpo_task_taks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taks',
            new_name='task',
        ),
    ]
